### ISSUE TITLE
ERROR: Default path '/tmp/kitchen' does not exist

### ISSUE THREAD

**Issue by wtanaka** [neillturner/kitchen-verifier-serverspec#11]
/tmp/kitchen does not seem to exist in every case:

https://travis-ci.org/wtanaka/ansible-roles/jobs/138792815

**Comment by wtanaka** [comment]
This works around the issue:
```
  additional_install_command: mkdir -p /tmp/kitchen
```

**Comment by neillturner** [comment]
we should just do this command always just in case

**Comment by neillturner** [comment]
closed in version 0.5.2
