### ISSUE TITLE
default_pattern and remote_exec unpack specs to suites subdir

### ISSUE THREAD

**Issue by cliles** [neillturner/kitchen-verifier-serverspec#26]
It seems that when the specs are copied to the remote instance they are unpacked as ```/tmp/verifier/suites/serverspec``` yet c8307cb61a5ae8c141ff89be6cdb021486f87806 removed the suites subdir. This

**Comment by neillturner** [comment]
Thanks for that. Well it was based on this PR Support for default pattern #15 I will put in the suites into the path.

**Comment by neillturner** [comment]
fixed in version 0.6.7

**Comment by cliles** [comment]
ty, 0.6.7 works well!
